# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-03 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import djongo.models
import postagger.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=10)),
                ('model_name', models.CharField(max_length=20)),
                ('model_version', models.CharField(max_length=6)),
                ('sentence', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=10)),
                ('auto_tag', djongo.models.ArrayModelField(model_container=postagger.models.WordTag)),
                ('verify_tag', djongo.models.ArrayModelField(model_container=postagger.models.UserTag)),
            ],
        ),
    ]
