# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-08 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20180731_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerjobs',
            name='task_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='workerjobs',
            name='task_status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
