# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-09 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20180808_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerjobs',
            name='task_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
