# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=5000)),
                ('sentiment', models.CharField(max_length=50)),
            ],
        ),
    ]
